apiVersion: v1
kind: Service
metadata:
  name: {{ include "dummy-chart.fullname" . }}
  labels:
    {{- include "dummy-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: {{ include "dummy-chart.name" . }}
